// <auto-generated />
using System;
using ContactApplication.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContactApplication.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220109090132_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ContactApplication.Models.CallLogs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Date")
                        .HasColumnType("integer");

                    b.Property<int?>("contact_id")
                        .HasColumnType("integer");

                    b.Property<string>("log_type")
                        .HasColumnType("text");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("log_id");

                    b.HasIndex("contact_id");

                    b.HasIndex("user_id");

                    b.ToTable("CallLogs");
                });

            modelBuilder.Entity("ContactApplication.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("ContactId");

                    b.HasIndex("user_id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("ContactApplication.Models.Login", b =>
                {
                    b.Property<int>("userIid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<int?>("userreg_id")
                        .HasColumnType("integer");

                    b.HasKey("userIid");

                    b.HasIndex("userreg_id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("ContactApplication.Models.Register", b =>
                {
                    b.Property<int>("userreg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("mobile_number")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("user_name")
                        .HasColumnType("text");

                    b.HasKey("userreg_id");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("ContactApplication.Models.CallLogs", b =>
                {
                    b.HasOne("ContactApplication.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("contact_id");

                    b.HasOne("ContactApplication.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ContactApplication.Models.Contact", b =>
                {
                    b.HasOne("ContactApplication.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("user_id");
                });

            modelBuilder.Entity("ContactApplication.Models.Login", b =>
                {
                    b.HasOne("ContactApplication.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("userreg_id");
                });
#pragma warning restore 612, 618
        }
    }
}
